using System;
using System.Collections.Generic;

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

namespace euler_2
{
    class Program
    {
        static void Main(string[] args)
        {
            var fibb = new List<int>() {1, 2};
            var sum = 2;
            while (true) {
                var nextFibb = fibb[0] + fibb[1];
                if (nextFibb > 4000000) {
                    break;
                }
                fibb.RemoveAt(0);
                fibb.Add(nextFibb);
                sum += nextFibb % 2 == 0 ? nextFibb : 0; 
            }
            Console.WriteLine($"Answer: {sum}");
        }
    }
}
